name: Generate Go from Proto

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Generated Repo
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.PAT_TOKEN }}
          path: gen-repo

      - name: Clone Proto Files Repository
        run: git clone https://github.com/aknur111/my-user-service-protos.git proto-repo

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.22"

      - name: Install protoc and plugins
        run: |
          sudo apt-get update && sudo apt-get install -y protobuf-compiler
          go install google.golang.org/protobuf/cmd/protoc-gen-go@latest
          go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest
          echo "$(go env GOPATH)/bin" >> $GITHUB_PATH

      - name: Generate Go Code from all Proto Files
        run: |
          cd proto-repo
          find . -name "*.proto" | while read proto_file; do
            echo "Generating from $proto_file"
            protoc \
              --go_out=../gen-repo \
              --go_opt=paths=source_relative \
              --go-grpc_out=../gen-repo \
              --go-grpc_opt=paths=source_relative \
              -I . \
              -I /usr/include \
              "$proto_file"
          done

      - name: Push Generated Code
        run: |
          cd gen-repo
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git diff --cached --quiet || git commit -m "chore: auto-generate from proto [skip ci]"
          git push origin main